language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - server/node_modules
  - client/node_modules
script:
- cd server
- npm install
- npm test
- cd ../client
- npm install
- npm test
- unset CI
- cd ../server
- npm run build
- cd ../client
- npm run build
- set CI
