language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - server/node_modules
  - client/node_modules
script:
- cd server
- npm install -g npm@5.6.0
#- npm test
- cd ../client
- npm install -g npm@5.6.0
#- npm test
- unset CI
- cd ../client
- npm run deploy
- cd ../server
- npm run build
- set CI
