language: node_js
node_js:
- 8.11.1
cache:
  directories:
  - node_modules
script:
- cd server
- npm test
- cd ../client
- npm test
- unset CI
- cd ../server
- npm run build
- cd ../client
- npm run build
- set CI
