---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devo-server
  labels:
    app: devo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devo-server
  template:
    metadata:
      labels:
        app: devo-server
    spec:
      containers:
        - image: gcr.io/ocismartdevice/devo-server
          name: devo-server
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-auth
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-auth
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-auth
                  key: password
          ports:
            - containerPort: 3001
              name: devo-server

---
apiVersion: v1
kind: Service
metadata:
  name: devo-server
  labels:
    app: devo-server
spec:
  type: ClusterIP
  ports:
    - port: 3001
  selector:
    app: devo-server
